-- Insert test users (only if not exists)
-- Password for all users: "password123"
-- BCrypt hash: $2a$10$ehbj8PYYhUqJE5uwtY4aNu3bupMD6BiUOt1xVEukO5o0bgudnhWUW

MERGE INTO USERS u
USING (SELECT 1 AS ID, 'admin' AS USERNAME, '$2a$10$ehbj8PYYhUqJE5uwtY4aNu3bupMD6BiUOt1xVEukO5o0bgudnhWUW' AS PASSWORD, 'ADMIN' AS ROLE, 1 AS IS_ACTIVE, 'Administrator' AS FULL_NAME FROM DUAL) src
ON (u.USERNAME = src.USERNAME)
WHEN NOT MATCHED THEN
  INSERT (ID, USERNAME, PASSWORD, ROLE, IS_ACTIVE, FULL_NAME)
  VALUES (src.ID, src.USERNAME, src.PASSWORD, src.ROLE, src.IS_ACTIVE, src.FULL_NAME);

MERGE INTO USERS u
USING (SELECT 2 AS ID, 'gdv01' AS USERNAME, '$2a$10$ehbj8PYYhUqJE5uwtY4aNu3bupMD6BiUOt1xVEukO5o0bgudnhWUW' AS PASSWORD, 'GDV' AS ROLE, 1 AS IS_ACTIVE, 'Vũ Thị Tâm' AS FULL_NAME FROM DUAL) src
ON (u.USERNAME = src.USERNAME)
WHEN NOT MATCHED THEN
  INSERT (ID, USERNAME, PASSWORD, ROLE, IS_ACTIVE, FULL_NAME)
  VALUES (src.ID, src.USERNAME, src.PASSWORD, src.ROLE, src.IS_ACTIVE, src.FULL_NAME);

MERGE INTO USERS u
USING (SELECT 3 AS ID, 'ksv01' AS USERNAME, '$2a$10$ehbj8PYYhUqJE5uwtY4aNu3bupMD6BiUOt1xVEukO5o0bgudnhWUW' AS PASSWORD, 'KSV' AS ROLE, 1 AS IS_ACTIVE, 'Hoàng Văn Thuận' AS FULL_NAME FROM DUAL) src
ON (u.USERNAME = src.USERNAME)
WHEN NOT MATCHED THEN
  INSERT (ID, USERNAME, PASSWORD, ROLE, IS_ACTIVE, FULL_NAME)
  VALUES (src.ID, src.USERNAME, src.PASSWORD, src.ROLE, src.IS_ACTIVE, src.FULL_NAME);

